apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-verticalworkloadautoscaler-viewer-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - autoscaling.workload.io
  resources:
  - verticalworkloadautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling.workload.io
  resources:
  - verticalworkloadautoscalers/status
  verbs:
  - get