---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - autoscaling.k8s.io
  resources:
  - workloadautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.k8s.io
  resources:
  - workloadautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.k8s.io
  resources:
  - workloadautoscalers/status
  verbs:
  - get
  - patch
  - update
