# permissions for end users to view verticalworkloadautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vertical-workload-autoscaler
    app.kubernetes.io/managed-by: kustomize
  name: verticalworkloadautoscaler-viewer-role
rules:
- apiGroups:
  - autoscaling.workload.io
  resources:
  - verticalworkloadautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling.workload.io
  resources:
  - verticalworkloadautoscalers/status
  verbs:
  - get
