apiVersion: autoscaling.workload.io/v1alpha1
kind: VerticalWorkloadAutoscaler
metadata:
  labels:
    app.kubernetes.io/name: vertical-workload-autoscaler
    app.kubernetes.io/managed-by: kustomize
  name: verticalworkloadautoscaler-sample
spec:
  vpaReference:
    name: my-vpa

  allowedUpdateWindows:
    - dayOfWeek: Monday
      startTime: "09:00"
      endTime: "17:00"
      timeZone: "UTC"
    - dayOfWeek: Friday
      startTime: "09:00"
      endTime: "12:00"
      timeZone: "UTC"

  avoidCPULimit: true
  customAnnotations:
    custom-key: custom-value
  ignoreCPURecommendations: false
  ignoreMemoryRecommendations: false
  qualityOfService: Guaranteed
  updateFrequency: 10m
  updateTolerance:
    cpu: 10
    memory: 10

status:
  lastUpdated: "2024-09-21T12:00:00Z"
  recommendedRequests:
    my-container:
      requests:
        cpu: "600m"
        memory: "600Mi"
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-deployment
  skipReason: "Change below step size"
  skippedUpdates: true
  updateCount: 3
  conditions:
    - type: Ready
      status: "True"
      lastTransitionTime: "2024-09-21T12:00:00Z"
      reason: Ready
      message: "VWA is ready and operational"
    - type: Updating
      status: "False"
      lastTransitionTime: "2024-09-21T12:00:00Z"
      reason: NoUpdateInProgress
      message: "No update is currently in progress"
  conflicts:
    - resource: my-deployment
      conflictWith: manual-setting
      reason: "Manually set resource limits conflict with VWA recommendations"