apiVersion: autoscaling.k8s.io.autoscaling.k8s.io/v1alpha1
kind: WorkloadAutoscaler
metadata:
  labels:
    app.kubernetes.io/name: workload-autoscaler
    app.kubernetes.io/managed-by: kustomize
  name: workloadautoscaler-sample
spec:
  # TODO(user): Add fields here
