//go:build !ignore_autogenerated

/*
Copyright 2024 Alexei Ledenev.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Conflict) DeepCopyInto(out *Conflict) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Conflict.
func (in *Conflict) DeepCopy() *Conflict {
	if in == nil {
		return nil
	}
	out := new(Conflict)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HPAReference) DeepCopyInto(out *HPAReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HPAReference.
func (in *HPAReference) DeepCopy() *HPAReference {
	if in == nil {
		return nil
	}
	out := new(HPAReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRequests) DeepCopyInto(out *ResourceRequests) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequests.
func (in *ResourceRequests) DeepCopy() *ResourceRequests {
	if in == nil {
		return nil
	}
	out := new(ResourceRequests)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateTolerance) DeepCopyInto(out *UpdateTolerance) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateTolerance.
func (in *UpdateTolerance) DeepCopy() *UpdateTolerance {
	if in == nil {
		return nil
	}
	out := new(UpdateTolerance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateWindow) DeepCopyInto(out *UpdateWindow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateWindow.
func (in *UpdateWindow) DeepCopy() *UpdateWindow {
	if in == nil {
		return nil
	}
	out := new(UpdateWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPAReference) DeepCopyInto(out *VPAReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPAReference.
func (in *VPAReference) DeepCopy() *VPAReference {
	if in == nil {
		return nil
	}
	out := new(VPAReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerticalWorkloadAutoscaler) DeepCopyInto(out *VerticalWorkloadAutoscaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerticalWorkloadAutoscaler.
func (in *VerticalWorkloadAutoscaler) DeepCopy() *VerticalWorkloadAutoscaler {
	if in == nil {
		return nil
	}
	out := new(VerticalWorkloadAutoscaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VerticalWorkloadAutoscaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerticalWorkloadAutoscalerList) DeepCopyInto(out *VerticalWorkloadAutoscalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VerticalWorkloadAutoscaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerticalWorkloadAutoscalerList.
func (in *VerticalWorkloadAutoscalerList) DeepCopy() *VerticalWorkloadAutoscalerList {
	if in == nil {
		return nil
	}
	out := new(VerticalWorkloadAutoscalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VerticalWorkloadAutoscalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerticalWorkloadAutoscalerSpec) DeepCopyInto(out *VerticalWorkloadAutoscalerSpec) {
	*out = *in
	out.VPAReference = in.VPAReference
	if in.UpdateFrequency != nil {
		in, out := &in.UpdateFrequency, &out.UpdateFrequency
		*out = new(v1.Duration)
		**out = **in
	}
	if in.AllowedUpdateWindows != nil {
		in, out := &in.AllowedUpdateWindows, &out.AllowedUpdateWindows
		*out = make([]UpdateWindow, len(*in))
		copy(*out, *in)
	}
	if in.UpdateTolerance != nil {
		in, out := &in.UpdateTolerance, &out.UpdateTolerance
		*out = new(UpdateTolerance)
		**out = **in
	}
	if in.CustomAnnotations != nil {
		in, out := &in.CustomAnnotations, &out.CustomAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerticalWorkloadAutoscalerSpec.
func (in *VerticalWorkloadAutoscalerSpec) DeepCopy() *VerticalWorkloadAutoscalerSpec {
	if in == nil {
		return nil
	}
	out := new(VerticalWorkloadAutoscalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerticalWorkloadAutoscalerStatus) DeepCopyInto(out *VerticalWorkloadAutoscalerStatus) {
	*out = *in
	out.ScaleTargetRef = in.ScaleTargetRef
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
	if in.RecommendedRequests != nil {
		in, out := &in.RecommendedRequests, &out.RecommendedRequests
		*out = make(map[string]corev1.ResourceRequirements, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conflicts != nil {
		in, out := &in.Conflicts, &out.Conflicts
		*out = make([]Conflict, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerticalWorkloadAutoscalerStatus.
func (in *VerticalWorkloadAutoscalerStatus) DeepCopy() *VerticalWorkloadAutoscalerStatus {
	if in == nil {
		return nil
	}
	out := new(VerticalWorkloadAutoscalerStatus)
	in.DeepCopyInto(out)
	return out
}
