apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-overprovisioned
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: alpine:3.20
          command: ["/bin/sh", "-c", "tail -f /dev/null"]
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi