name: pr-review-agent

on:
  pull_request:
    types: [ opened, reopened, ready_for_review, synchronize ]
  issue_comment:
    types: [ created ]

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run PR Agent
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: review PR
        uses: Codium-ai/pr-agent@v0.24
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_REVIEWER.REQUIRE_TESTS_REVIEW: "false"
          PR_CODE_SUGGESTIONS.NUM_CODE_SUGGESTIONS: 5